# Generated by Django 3.2.13 on 2022-05-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fashion_name', models.CharField(max_length=200)),
                ('fashion_loc', models.CharField(max_length=100)),
                ('fashion_img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
