# Generated by Django 3.2.13 on 2022-05-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProjectA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fash_name', models.CharField(max_length=200)),
                ('fash_content', models.CharField(max_length=300)),
                ('fash_img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
